// bundled_fonts.cpp — see bundled_fonts.hpp.
//
// At build time `pulp_add_binary_data(pulp-bundled-fonts SOURCES …)` produces
// `pulp-bundled-fonts_data.hpp`, which declares one `extern const unsigned
// char <name>[]` + `<name>_size` per embedded asset. We mirror that list here
// so we can iterate over every bundled .ttf without scraping CMake state at
// runtime.
//
// If `PULP_HAS_SKIA` is not defined we still ship a translation unit so the
// header has *something* to link against in non-GPU builds; the entry points
// are gated on the same macro.

#include <pulp/canvas/bundled_fonts.hpp>

#ifdef PULP_HAS_SKIA

#include <array>
#include <mutex>
#include <string>
#include <unordered_map>

#include "include/core/SkData.h"
#include "include/core/SkFontMgr.h"
#include "include/core/SkString.h"
#include "include/core/SkTypeface.h"

#include "pulp-bundled-fonts_data.hpp" // Generated by pulp_add_binary_data.

namespace pulp::canvas {

namespace {

struct BundledBlob {
    const char* asset_name;       // Original file name (for diagnostics).
    const unsigned char* data;
    std::size_t size;
};

// One entry per .ttf listed in core/canvas/CMakeLists.txt. Keep this list and
// the CMake SOURCES list in sync — there is intentionally no auto-discovery,
// so failures show up as a "file not declared" link error rather than a
// silent runtime miss.
const std::array<BundledBlob, 2>& bundled_blobs() {
    static const std::array<BundledBlob, 2> kBlobs = {{
        {"Inter-Regular.ttf",
         pulp_bundled_fonts::Inter_Regular_ttf,
         pulp_bundled_fonts::Inter_Regular_ttf_size},
        {"JetBrainsMono-Regular.ttf",
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf,
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf_size},
    }};
    return kBlobs;
}

// First call with a non-null `mgr` lazily materialises every blob into an
// SkTypeface keyed by the face's reported family name (NOT the file name —
// we trust Skia's name table parse over our naming convention). Lookup is
// O(1) average.
//
// The `mgr` argument is forwarded only on the initialising call; subsequent
// callers reuse the cache regardless of which font manager they hand in.
// We deliberately do NOT call `std::call_once` here: if the very first
// caller passes a null manager (e.g. a unit test that is verifying graceful
// degradation), `call_once` would burn the once-flag and the *next* caller
// with a real mgr would see an empty cache forever. Use a guard flag that
// only flips on success.
const std::unordered_map<std::string, sk_sp<SkTypeface>>&
ensure_registered(SkFontMgr* mgr) {
    static std::mutex lock;
    static bool initialized = false;
    static std::unordered_map<std::string, sk_sp<SkTypeface>> by_family;

    std::lock_guard<std::mutex> guard(lock);
    if (initialized || !mgr) return by_family;

    for (const auto& blob : bundled_blobs()) {
        if (!blob.data || blob.size == 0) continue;
        // SkData::MakeWithoutCopy is safe here: the array data has static
        // storage duration (lives for the entire process) and the
        // SkTypeface only holds a reference for as long as it's in our
        // cache, which is also static.
        auto sk_data = SkData::MakeWithoutCopy(blob.data, blob.size);
        sk_sp<SkTypeface> face = mgr->makeFromData(std::move(sk_data));
        if (!face) continue;

        SkString family;
        face->getFamilyName(&family);
        if (family.isEmpty()) continue;

        // First face wins for a given family. The bundle currently has at
        // most one face per family, so collisions just mean we shipped a
        // duplicate — keep the first deterministically.
        by_family.emplace(std::string(family.c_str()), std::move(face));
    }

    initialized = true;
    return by_family;
}

} // namespace

sk_sp<SkTypeface> match_bundled_typeface(SkFontMgr* mgr,
                                         const std::string& family,
                                         SkFontStyle style) {
    const auto& cache = ensure_registered(mgr);
    auto it = cache.find(family);
    if (it == cache.end()) return nullptr;

    // The bundle currently ships only Regular/Upright faces. If the caller
    // wants something else (bold, italic, …) we MUST return nullptr so the
    // skia_canvas typeface lookup keeps walking and lets
    // SkFontMgr::matchFamilyStyle pick a system-installed bold/italic
    // variant — otherwise #932 silently regresses #927's weight/slant
    // honouring (Codex P2 on PR #956).
    SkFontStyle have = it->second->fontStyle();
    if (have.weight() != style.weight() || have.slant() != style.slant()) {
        return nullptr;
    }
    return it->second;
}

std::size_t bundled_font_count() {
    return bundled_blobs().size();
}

} // namespace pulp::canvas

#endif // PULP_HAS_SKIA
